const mongoose = require('mongoose');

const MONGODB_URI = 'mongodb://Mubarak:ddZFO2wQQWQV6DMi@dml-cluster-shard-00-00.3j5lw.mongodb.net:27017,dml-cluster-shard-00-01.3j5lw.mongodb.net:27017,dml-cluster-shard-00-02.3j5lw.mongodb.net:27017/ict-learner-nigeria?ssl=true&replicaSet=atlas-12fagn-shard-0&authSource=admin&appName=dml-cluster';
const TEACHER_ID = new mongoose.Types.ObjectId('69cd0630b527fd1a358fe69c');

async function seed() {
  try {
    console.log('--- 🚀 Seeding Educational Content Cluster ---');
    await mongoose.connect(MONGODB_URI);
    const db = mongoose.connection.db;

    console.log('🧹 Clearing existing subjects, topics, and modules...');
    await db.collection('subjects').deleteMany({});
    await db.collection('topics').deleteMany({});
    await db.collection('modules').deleteMany({});
    // Depending on the collection name used by Mongoose:
    await db.collection('ict-learner-nigeria').deleteMany({}); // if using the explicit collection name for Subjects
    await db.collection('ict-learner-nigeria-topics').deleteMany({});
    await db.collection('ict-learner-nigeria-modules').deleteMany({});

    console.log('📂 Creating Subjects...');
    const digitalLiteracyId = new mongoose.Types.ObjectId();
    await db.collection('ict-learner-nigeria').insertOne({
      _id: digitalLiteracyId,
      title: 'Digital Literacy & Computer Studies',
      description: 'Foundational concepts for the modern digital landscape in Nigeria. Scaffolding technical competence and critical thinking.',
      icon: '💻',
      color: '#10b981',
      allowedContexts: ['General', 'Junior Secondary'],
      createdBy: TEACHER_ID,
      createdAt: new Date(),
      updatedAt: new Date()
    });

    const cyberSecurityId = new mongoose.Types.ObjectId();
    await db.collection('ict-learner-nigeria').insertOne({
      _id: cyberSecurityId,
      title: 'Cybersecurity & Digital Ethics',
      description: 'Navigating the risks and responsibilities of our hyper-connected world. Constructing safe digital identities.',
      icon: '🛡️',
      color: '#6366f1',
      allowedContexts: ['General', 'Senior Secondary'],
      createdBy: TEACHER_ID,
      createdAt: new Date(),
      updatedAt: new Date()
    });

    console.log('📚 Creating Topics...');
    const hardwareFundId = new mongoose.Types.ObjectId();
    await db.collection('ict-learner-nigeria-topics').insertOne({
      _id: hardwareFundId,
      title: 'Computer Hardware Ecosystems',
      description: 'Understanding the physical components that power our digital experiences.',
      category: 'Hardware',
      subjectId: digitalLiteracyId,
      createdBy: TEACHER_ID,
      createdAt: new Date(),
      updatedAt: new Date()
    });

    console.log('✨ Creating 5E Modules...');
    
    // Module: I/O Devices using exact format generated by Gemini 2.5 Flash
    await db.collection('ict-learner-nigeria-modules').insertOne({
      title: 'The Binary Interface: I/O Devices',
      content: 'Exploring how we communicate with computers and how they respond to us. This covers basic peripherals to advanced biometric scanners.',
      topicId: hardwareFundId,
      type: 'activity',
      
      // 5E Core generated by the AI
      engage: 'Have you ever tried to type on a screen with water on your fingers? Why does it fail? What physical bridges connect our chaotic human world to the perfectly structured digital world of a computer?',
      explore: 'Find 3 devices in your home that connect to the internet. Which parts of those devices "listen" to you, and which parts "speak" to you? Draw a diagram of this flow.',
      explain: 'Input devices (like keyboards, mice, and sensors) encode physical phenomena into binary data. Output devices (like screens and speakers) decode binary data back into physical phenomena (light, sound, motion).',
      elaborate: {
        'General': 'Ever wonder how a biometric fingerprint scanner at a bank works? It acts as an input device, taking your physical identity and safely translating it for digital validation.',
        'Junior Secondary': 'Think of input devices as the "ears and eyes" of your PC, and output devices as the "mouth and hands". If you play a video game, the controller is the input, and the TV is the output.'
      },
      evaluate: 'Reflection: If you had to invent a new input device for someone who cannot use their hands, what would it measure and how would it work?',
      constructivistNote: 'This module forces the learner to anchor the abstract concept of I/O to tangible objects in their immediate environment, maximizing cognitive retention.',
      questions: [
        {
          question: 'Which of the following is strictly an input device?',
          options: ['Monitor', 'Keyboard', 'Speaker', 'Printer'],
          correctAnswer: 1,
          explanation: 'A keyboard only sends data to the computer; it cannot display or generate data back to the user.'
        },
        {
          question: 'Is a Touchscreen an Input or Output device?',
          options: ['Input only', 'Output only', 'Both Input and Output', 'Neither'],
          correctAnswer: 2,
          explanation: 'A touchscreen is a sensing surface (Input) overlaid on top of a display (Output), performing both functions simultaneously.'
        },
        {
          question: 'What is the primary function of an Output device?',
          options: ['To store binary data for later use.', 'To translate binary data into human-perceivable forms like light or sound.', 'To encode physical actions into digital signals.', 'To cool down the CPU.'],
          correctAnswer: 1,
          explanation: 'Output devices take the processed digital results and translate them into something we can see, hear, or feel.'
        }
      ],
      createdBy: TEACHER_ID,
      createdAt: new Date(),
      updatedAt: new Date()
    });

    console.log('🏁 Seeding Completed Successfully! 🏳️');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding Error:', error);
    process.exit(1);
  }
}

seed();
